apiVersion: v2
name: zot-fork
description: zot OCI registry — managed fork with CVE security patches
type: application
version: 1.0.0
appVersion: "2.1.15-r1"
maintainers:
  - name: REPLACE_NAME
    email: REPLACE_EMAIL
keywords:
  - foss
  - security
  - patched
